### ISSUE TITLE
failing on adding repo 

### ISSUE THREAD

**Issue by sprasad09** [TalAntR/ansible-collectd#12]
TASK [collectd : add repositories] *************************************************************************************************************************************************************************
fatal: [172.31.4.231]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'name'\n\nThe error appears to have been in '/etc/ansible/roles/collectd/tasks/debian/prepare.yml': line 19, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: add repositories\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'name'"}

my ansible version:

ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

**Comment by TalAntR** [comment]
Hi @sprasad09,

Could you provide your playbook? I'd like to see how the variables were declared.
